### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by AntonOks** [raku-community-modules/Test-Output#12]
WARNING: Version mismatch for Test-Output ("https://github.com/raku-community-modules/perl6-Test-Output.git") found. META6.json has "1.001005" but latest 'git tag' is "v1.001001"

**Comment by AntonOks** [comment]
@sdondley @JJ @lizmat  ping

**Comment by 2colours** [comment]
1.001006 is released via Fez and tagged.

**Comment by AntonOks** [comment]
THANKS.

The Star [modules.txt was already auto-updated](https://github.com/rakudo/star/commit/57bc7ae4a30d483d323e4cd0909cfd45d02804dc). The next Star will ship with this version :)
