### ISSUE TITLE
catch error when using stderr-like

### ISSUE THREAD

**Issue by finanalyst** [raku-community-modules/Test-Output#2]
I have in a test file that includes:
```perl6
stderr-like {$cache = Pod::Cached.new(:source<t/tmp/doc>, :path<t/tmp/ref>, :verbose ) },
    /'Cache verified'/, 'verbose flag generates output on stderr';
```
The result of the test is a complete exit from `prove -ve perl6 ` with output:
```
No exception handler located for catch
   at SETTING::src/core/Exception.pm6:395  (/home/richard/rakudo/install/share/perl6/runtime/CORE.setting.moarvm:print_exception)
 from SETTING::src/core/Exception.pm6:452  (/home/richard/rakudo/install/share/perl6/runtime/CORE.setting.moarvm:<anon>)
 from gen/moar/stage2/NQPHLL.nqp:1732  (/home/richard/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/home/richard/rakudo/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1654  (/home/richard/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/richard/rakudo/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/richard/rakudo/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/richard/rakudo/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/richard/rakudo/install/share/perl6/runtime/perl6.moarvm:<entry>)
```
I replaced a `note` with a `exit note` and got this. Clearly the test should not pass, but I would think there should be some less drastic failure within a test file.

**Comment by finanalyst** [comment]
Problem not quite as described. The module being tested encountered a `die $condition-not-met` statement. So a Fatal Exception is being thrown when the test is expecting only a message on std-err. 

Even so, it seems to me that there should be an exception handler here so that the whole test run does not die.

**Comment by zoffixznet** [comment]
You could guard your code with a `try` if you don't want the program to exit the standard way.

Feels like capturing exceptions and doing something custom with them is outside the scope of this module

**Comment by finanalyst** [comment]
I accept that the module is designed for capturing output, and not exceptions+output. But it seemed to me that the error message 'no exception handler for catch' is non-standard. It was a surprise.
